/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingStep2RouteImport } from './routes/onboarding/step-2'
import { Route as OnboardingStep1RouteImport } from './routes/onboarding/step-1'
import { Route as OnboardingPlannerStep2RouteImport } from './routes/onboarding/planner-step-2'
import { Route as OnboardingPlannerStep1RouteImport } from './routes/onboarding/planner-step-1'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppExpensesIndexRouteImport } from './routes/_app/expenses/index'
import { Route as AppExpensesExpenseIdRouteImport } from './routes/_app/expenses/$expenseId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep2Route = OnboardingStep2RouteImport.update({
  id: '/onboarding/step-2',
  path: '/onboarding/step-2',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep1Route = OnboardingStep1RouteImport.update({
  id: '/onboarding/step-1',
  path: '/onboarding/step-1',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPlannerStep2Route = OnboardingPlannerStep2RouteImport.update({
  id: '/onboarding/planner-step-2',
  path: '/onboarding/planner-step-2',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPlannerStep1Route = OnboardingPlannerStep1RouteImport.update({
  id: '/onboarding/planner-step-1',
  path: '/onboarding/planner-step-1',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExpensesExpenseIdRoute = AppExpensesExpenseIdRouteImport.update({
  id: '/expenses/$expenseId',
  path: '/expenses/$expenseId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clients': typeof AppClientsRoute
  '/events': typeof AppEventsRoute
  '/overview': typeof AppOverviewRoute
  '/payments': typeof AppPaymentsRoute
  '/settings': typeof AppSettingsRoute
  '/onboarding/planner-step-1': typeof OnboardingPlannerStep1Route
  '/onboarding/planner-step-2': typeof OnboardingPlannerStep2Route
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/expenses/$expenseId': typeof AppExpensesExpenseIdRoute
  '/expenses/': typeof AppExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clients': typeof AppClientsRoute
  '/events': typeof AppEventsRoute
  '/overview': typeof AppOverviewRoute
  '/payments': typeof AppPaymentsRoute
  '/settings': typeof AppSettingsRoute
  '/onboarding/planner-step-1': typeof OnboardingPlannerStep1Route
  '/onboarding/planner-step-2': typeof OnboardingPlannerStep2Route
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/expenses/$expenseId': typeof AppExpensesExpenseIdRoute
  '/expenses': typeof AppExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/onboarding/planner-step-1': typeof OnboardingPlannerStep1Route
  '/onboarding/planner-step-2': typeof OnboardingPlannerStep2Route
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/_app/expenses/$expenseId': typeof AppExpensesExpenseIdRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/clients'
    | '/events'
    | '/overview'
    | '/payments'
    | '/settings'
    | '/onboarding/planner-step-1'
    | '/onboarding/planner-step-2'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/expenses/$expenseId'
    | '/expenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/clients'
    | '/events'
    | '/overview'
    | '/payments'
    | '/settings'
    | '/onboarding/planner-step-1'
    | '/onboarding/planner-step-2'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/expenses/$expenseId'
    | '/expenses'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/clients'
    | '/_app/events'
    | '/_app/overview'
    | '/_app/payments'
    | '/_app/settings'
    | '/onboarding/planner-step-1'
    | '/onboarding/planner-step-2'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/_app/expenses/$expenseId'
    | '/_app/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  OnboardingPlannerStep1Route: typeof OnboardingPlannerStep1Route
  OnboardingPlannerStep2Route: typeof OnboardingPlannerStep2Route
  OnboardingStep1Route: typeof OnboardingStep1Route
  OnboardingStep2Route: typeof OnboardingStep2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-2': {
      id: '/onboarding/step-2'
      path: '/onboarding/step-2'
      fullPath: '/onboarding/step-2'
      preLoaderRoute: typeof OnboardingStep2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-1': {
      id: '/onboarding/step-1'
      path: '/onboarding/step-1'
      fullPath: '/onboarding/step-1'
      preLoaderRoute: typeof OnboardingStep1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/planner-step-2': {
      id: '/onboarding/planner-step-2'
      path: '/onboarding/planner-step-2'
      fullPath: '/onboarding/planner-step-2'
      preLoaderRoute: typeof OnboardingPlannerStep2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/planner-step-1': {
      id: '/onboarding/planner-step-1'
      path: '/onboarding/planner-step-1'
      fullPath: '/onboarding/planner-step-1'
      preLoaderRoute: typeof OnboardingPlannerStep1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/expenses/$expenseId': {
      id: '/_app/expenses/$expenseId'
      path: '/expenses/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof AppExpensesExpenseIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppClientsRoute: typeof AppClientsRoute
  AppEventsRoute: typeof AppEventsRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppExpensesExpenseIdRoute: typeof AppExpensesExpenseIdRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppClientsRoute: AppClientsRoute,
  AppEventsRoute: AppEventsRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppExpensesExpenseIdRoute: AppExpensesExpenseIdRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  OnboardingPlannerStep1Route: OnboardingPlannerStep1Route,
  OnboardingPlannerStep2Route: OnboardingPlannerStep2Route,
  OnboardingStep1Route: OnboardingStep1Route,
  OnboardingStep2Route: OnboardingStep2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
